Update Ko.po
DawnbrandBots/bastion-bot pull request #210
Opened 2022-10-20 11:48 UTC by JSY1728

p.m. 20:47 | South Korea

2022-10-21 03:11 UTC, kevinlul requested changes

2022-10-21 03:11 UTC, kevinlul commented on translations/ko.po
> +msgstr ":말풍선: 번역이 누락되었습니까?"
I should just put the actual Unicode emojis here... this is actually 💬 !

2022-10-21 11:29 UTC, JSY1728 commented on translations/ko.po
> +msgstr ":말풍선: 번역이 누락되었습니까?"
i changed "말풍선" => "💬"

2022-10-22 03:26 UTC, kevinlul approved these changes
Thanks! 🚀 These changes will be live on the next deployment (not immediately).

2022-10-22 03:26 UTC, merged