update ja.po
DawnbrandBots/bastion-bot pull request #289
Opened 2023-02-26 07:34 UTC by myyourcaramel

2023-02-27 05:05 UTC, kevinlul requested changes

2023-02-27 05:05 UTC, kevinlul commented on translations/ja.po
> +msgstr "無料でオープンソースな _Yu-Gi-Oh!_ ボット"
Although I don't know the language, I think it should be 自由 here over 無料. While Bastion does come at no cost to the user, this expression is invoking [this concept](https://ja.wikipedia.org/wiki/FLOSS) (not sure if there's a better article in the language).

2023-02-27 07:38 UTC, myyourcaramel commented on translations/ja.po
> +msgstr "無料でオープンソースな _Yu-Gi-Oh!_ ボット"
Oh yes! Free can have sereral translations and it means _Libre_ (自由) here.

2023-02-28 04:20 UTC, kevinlul approved these changes
Thank you!

2023-02-28 04:21 UTC, merged